#!/usr/bin/env ruby
#coding:utf-8

require "securerandom"
require "net/http"
require "json"

services = %w{
  web
  admin
  api
}

http = Net::HTTP.new("127.0.0.1", 3000)
http.read_timeout = 0.1

1000.times do
  uuid = SecureRandom.uuid
  service = services.sample

  out = [
    "id=#{uuid}",
    "service_name=#{service}",
    "process=#{service}.#{rand(1..4000)}",
    "sample#load_avg_1m=#{rand.round(3)}",
    "sample#load_avg_5m=#{rand.round(3)}",
    "sample#load_avg_15m=#{rand.round(3)}",
  ].join(" ")

  begin
    http.request_post("/", JSON.generate({log: out})) {}
  rescue Net::ReadTimeout
    puts "Remote server timed-out on http://127.0.0.1:3000"
  rescue Errno::ECONNREFUSED
    puts "Connection refused on http://127.0.0.1:3000"
  end
end
